morning-night-guild/platform-app

README.md, go.mod, renovate.json
=> #3 リポジトリを整備

e2e/appapi/article/share_test.go, internal/adapter/api/api.go, internal/adapter/api/api_test.go, internal/adapter/api/article.go
@Shitomo 
nilがリクエストに含まれていてもpanicしないように修正しました。
=> #16 nilがリクエストに含まれてもpanicしないように修正

.docker/docker-compose.yaml, e2e/appapi/article/list_test.go, e2e/appcore/article/list_test.go, e2e/helper/id.go, go.mod, go.sum, internal/adapter/api/api.go, internal/adapter/api/article.go, internal/adapter/api/helth.go, internal/driver/interceptor/interceptor.go, internal/driver/middleware/middleware.go, pkg/log/context.go, pkg/trace/context.go, pkg/trace/trace.go, vendor/github.com/oklog/ulid/v2/.gitignore, vendor/github.com/oklog/ulid/v2/AUTHORS.md, vendor/github.com/oklog/ulid/v2/CHANGELOG.md, vendor/github.com/oklog/ulid/v2/CONTRIBUTING.md, vendor/github.com/oklog/ulid/v2/LICENSE, vendor/github.com/oklog/ulid/v2/README.md, vendor/github.com/oklog/ulid/v2/ulid.go, vendor/modules.txt
@Shitomo 
トレースIDを設定しました。
AppAPIからAppCoreまで追えるようにしてみました。
=> #18 トレースIDを設定

Makefile, internal/usecase/interactor/api_article_list_test.go, internal/usecase/interactor/api_article_share_test.go, internal/usecase/interactor/api_health_check_test.go, internal/usecase/interactor/core_list_test.go, internal/usecase/interactor/core_share_test.go, internal/usecase/mock/api_article.go, internal/usecase/mock/api_health.go
@Shitomo 
usecaseに関するunit testを追加しました。
=> #24 usecaseに関する単体テストを追加

.github/workflows/container.deploy.yaml
@Shitomo 
renovateの修正がちょこちょこ入るので金夜に自動デプロイするように設定しました。
=> chore(#38) 金曜夜に自動デプロイが実行されるように条件を設定

.github/workflows/auto.go.mod.yaml, .github/workflows/auto.pr.merge.yaml
@Shitomo 
CI上で依存関係を更新するように設定しました。
=> #49 renovate発火時に依存関係をCIにて更新するように設定

cmd/db2db/entrypoint.sh, cmd/db2db/main.go, cmd/migrate/main.go
@Shitomo 
データ移行用のスクリプトを実装しました。
`export`で指定したリモートDBからローカルDBへデータを移行し
`import`で指定したリモートDBへローカルからデータを移行できます。
（気軽にデータ触れちゃうのなんか嫌だな。。。）
=> #51 データ移行スクリプトを実装

.github/workflows/auto.go.mod.yaml, .github/workflows/container.build.yaml, .github/workflows/container.deploy.yaml, .github/workflows/diff.gen.code.yaml, .github/workflows/lint.go.yaml, .github/workflows/lint.proto.yaml, .github/workflows/lint.yaml.yaml, .github/workflows/vulnerability.yaml
Reverts morning-night-guild/platform-app#75
=> Revert "(auto merged) Update dependency aquaproj/aqua to v2"

.github/workflows/auto.pr.merge.yaml
https://aquaproj.github.io/docs/reference/upgrade-guide/v2/
v2対応までオートマージを切ります。
=> #80 オートマージ対象ブランチ名を修正

aqua.yaml, registry.yaml
- https://github.com/morning-night-guild/platform-app/issues/83
=> chore(aqua): replace the local Registry to the Stanard Registry

api/openapi.yaml, e2e/appapi/article/list_test.go, e2e/appapi/article/share_test.go, internal/adapter/handler/article.go, internal/adapter/handler/article_test.go, internal/adapter/handler/auth.go, internal/adapter/handler/helth.go, pkg/openapi/client.gen.go, pkg/openapi/server.gen.go, pkg/openapi/types.gen.go
=> #98 認証機能のAPIを追加

cmd/app/api/main.go, internal/adapter/kvs/kvs.go, internal/usecase/interactor/api_auth_refresh.go, internal/usecase/interactor/api_auth_refresh_test.go
@Shitomo 
リフレッシュ時にauthをcacheに保存するように修正しました。
=> #120 リフレッシュ時にauthをcacheに保存するように修正

.github/workflows/lint.go.yaml, .golangci.yaml, Makefile, aqua.yaml, go.mod, internal/adapter/controller/health.go, internal/adapter/controller/user.go, internal/adapter/handler/auth.go, internal/adapter/handler/helth.go, internal/driver/config/api_test.go, internal/driver/config/core_test.go, internal/usecase/interactor/api_health_check.go, internal/usecase/interactor/core_user_create.go
@Shitomo 
Goのバージョンを1.20 に更新しました。
=> #130 Go1.20

.github/workflows/lint.go.yaml, Makefile, cmd/db/backup/main.go, pkg/ent/client.go, pkg/ent/generate.go, pkg/ent/tx.go
@Shitomo 
backup実行時に既存テーブルを削除するように修正しました。
=> #133 backup実行時に既存テーブルを削除

.docker/test.docker-compose.yaml, .env.local, .github/workflows/lint.go.yaml, .github/workflows/test.integration.yaml, Makefile, integration/external/external_test.go, integration/gateway/gateway_test.go, integration/helper/helper.go, integration/helper/helper_test.go, integration/kvs/kvs_test.go, internal/driver/postgres/postgres.go
=> #154 統合テストを追加

.docker/firebase/Dockerfile, internal/adapter/external/article.go, internal/adapter/external/connect.go, internal/adapter/external/health.go, internal/adapter/external/user.go, internal/adapter/handler/auth.go, internal/adapter/handler/handler.go, internal/domain/model/auth/auth_token.go, internal/domain/model/auth/auth_token_test.go, internal/domain/model/user.go, internal/domain/model/user_test.go, internal/driver/interceptor/interceptor.go, internal/driver/middleware/middleware.go
@Shitomo 
UserIDをサーバー間で伝播するように実装しました。
=> #165 UserIDを伝播する

integration/kvs/kvs_test.go, internal/adapter/kvs/kvs.go, internal/application/interactor/api_auth.go, internal/application/interactor/api_auth_test.go, internal/domain/cache/cache.go, internal/domain/cache/cache_mock.go
@Shitomo 
KVSにトランザクションを導入しました。
=> #170 KVSにトランザクションを導入

README.md
=> #184 README.mdを更新

internal/adapter/controller/article.go, internal/adapter/controller/article_test.go, internal/adapter/controller/controller.go, internal/adapter/controller/controller_test.go, internal/adapter/controller/health.go, internal/adapter/controller/health_test.go, internal/adapter/controller/user.go, internal/adapter/controller/user_test.go, internal/adapter/external/article.go, internal/adapter/external/auth.go, internal/adapter/external/health.go, internal/adapter/external/user.go, internal/adapter/gateway/article.go, internal/adapter/gateway/user.go, internal/application/interactor/api_article.go, internal/application/interactor/api_article_test.go, internal/application/interactor/api_auth.go, internal/application/interactor/api_auth_test.go, internal/application/interactor/api_health.go, internal/application/interactor/api_health_test.go, internal/application/interactor/core_article.go, internal/application/interactor/core_article_test.go, internal/application/interactor/core_user.go, internal/application/interactor/core_user_test.go
@Shitomo 
変数名を修正しました。
コード自動生成するときとかに脳死で設定できたりするかもです。
=> #192 各種変数名を修正

api/openapi.yaml, cmd/app/api/main.go, e2e/appapi/auth/sign_out_all_test.go, integration/kvs/kvs_test.go, internal/adapter/handler/auth.go, internal/adapter/handler/auth_test.go, internal/adapter/handler/handler.go, internal/adapter/kvs/kvs.go, internal/application/interactor/api_auth.go, internal/application/interactor/api_auth_test.go, internal/application/usecase/api_auth.go, internal/application/usecase/api_auth_mock.go, internal/domain/cache/cache.go, internal/domain/cache/cache_mock.go, internal/domain/model/session.go, internal/domain/model/session_test.go, pkg/ent/article_query.go, pkg/ent/articletag_query.go, pkg/ent/generate.go, pkg/ent/user_query.go, pkg/openapi/client.gen.go, pkg/openapi/server.gen.go, vendor/entgo.io/ent/dialect/sql/sqljson/dialect.go, vendor/entgo.io/ent/dialect/sql/sqljson/sqljson.go, vendor/modules.txt
@Shitomo 
全セッションを削除する機能を追加しました。
=> #195 サインアウト時に全セッションを削除する機能を追加

.github/workflows/auto.go.mod.yaml, .github/workflows/notice.aqua.pr.yaml
@Shitomo 
aquaのprを月一でチェックしてURLをslackに通知するように設定しました。
=> #176 aquaのprを月一でマージするように通知する設定を追加

api/openapi.yaml, e2e/appapi/auth/change_password_test.go, internal/adapter/external/auth.go, internal/adapter/external/external.go, internal/adapter/handler/article.go, internal/adapter/handler/auth.go, internal/adapter/handler/auth_test.go, internal/application/interactor/api_auth.go, internal/application/interactor/api_auth_test.go, internal/application/usecase/api_auth.go, internal/application/usecase/api_auth_mock.go, internal/domain/model/auth/password.go, internal/domain/model/auth/password_test.go, internal/domain/model/user.go, internal/domain/model/user/id.go, internal/domain/model/user/id_test.go, internal/domain/model/user_test.go, internal/domain/rpc/auth.go, internal/domain/rpc/auth_mock.go, internal/driver/interceptor/interceptor.go, pkg/openapi/client.gen.go, pkg/openapi/server.gen.go, pkg/openapi/types.gen.go
@Shitomo 
パスワード変更機能を実装しました。
すべてのセッションからサインアウトする機能も修正しました。
=> #220 パスワード変更機能を実装

integration/kvs/kvs_test.go, internal/adapter/kvs/kvs.go, internal/application/interactor/api_auth.go, internal/application/interactor/api_auth_test.go, internal/domain/cache/cache.go, internal/domain/cache/cache_mock.go, internal/domain/model/code.go
@Shitomo 
認証機能をリファクタリングしました。
- Redisからキー一覧を取得するロジックを修正
- サインアウトオール時にすべての User キャッシュを削除する
（消さなくても機能に影響はないが30日無駄なリソースを使うのが嫌なので対応）
=> #222 認証機能をリファクタリング
